export const KEYWORDS = [
	"full stack",
	"full-stack",
	"fullstack",
	"front end",
	"front-end",
	"frontend",
	"back end",
	"back-end",
	"backend",
	"javascript",
	"html",
	"css",
	"devops",
	"react",
	"next.js",
	"nextjs",
	"next js",
	"node.js",
	"nodejs",
	"node js",
	"web",
	"software",
	"developer",
	"desenvolvedor",
	"application",
	"aplicação",
	"systems",
	"sistemas",
	"technical lead",
	"líder técnico",
	"solutions architect",
	"arquiteto de soluções",
	"systems analyst",
	"analista de sistemas",
	"code quality",
	"qualidade de código",
	"mobile",
	"aplicativos",
	"banco de talentos",
];
