name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      uses: docker/login-action@v3.0.0
      with:
        username: bielsz
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bielsz/onlyjobs:latest
    - name: Push image to Docker Hub
      run: docker push bielsz/onlyjobs:latest
